repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
    exclude: ^tests/?.*/assets/.+
  - id: end-of-file-fixer
    exclude: ^tests/?.*/assets/.+
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.9.15
  hooks:
    - id: uv-lock
      name: check uv.lock file matches pyproject
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.7
  hooks:
    - id: ruff
      name: run linter
      args: [ --fix, --show-fixes ]
    - id: ruff-format
      name: run formatter
